-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  billing_address jsonb
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for subscription plans
create table plans (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  website_limit int not null,
  razorpay_plan_id text unique
);

-- Create a table for subscriptions
create table subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  plan_id bigint references plans not null,
  status text check (status in ('active', 'canceled', 'past_due')) not null,
  razorpay_subscription_id text unique,
  current_period_start timestamptz not null,
  current_period_end timestamptz not null
);

alter table subscriptions
  enable row level security;

create policy "Users can view their own subscriptions." on subscriptions
  for select using (auth.uid() = user_id);

-- Create a table for master templates
create table templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  preview_url text
);

-- Create a table for user websites
create table websites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  template_id bigint references templates not null,
  site_slug text not null unique,
  is_published boolean default false,
  website_data jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table websites
  enable row level security;

create policy "Users can manage their own websites." on websites
  for all using (auth.uid() = user_id);

-- Create tables for e-commerce functionality
create table categories (
  id bigint generated by default as identity primary key,
  website_id bigint references websites not null,
  name text not null
);

create table products (
  id bigint generated by default as identity primary key,
  website_id bigint references websites not null,
  category_id bigint references categories,
  name text not null,
  description text,
  price numeric not null,
  unit text,
  image_url text
);

create table customers (
  id bigint generated by default as identity primary key,
  website_id bigint references websites not null,
  email text,
  name text,
  shipping_address jsonb
);

create table orders (
  id bigint generated by default as identity primary key,
  website_id bigint references websites not null,
  customer_id bigint references customers,
  total_amount numeric not null,
  status text check (status in ('pending', 'paid', 'shipped', 'delivered', 'canceled')),
  created_at timestamptz default now()
);

create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders not null,
  product_id bigint references products not null,
  quantity int not null,
  price numeric not null
);

-- Enable RLS for e-commerce tables, assuming website owners can see their own data
alter table categories enable row level security;
alter table products enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

create policy "Website owners can manage their own e-commerce data." on categories
  for all using (exists (select 1 from websites where websites.id = categories.website_id and websites.user_id = auth.uid()));

create policy "Website owners can manage their own e-commerce data." on products
  for all using (exists (select 1 from websites where websites.id = products.website_id and websites.user_id = auth.uid()));

create policy "Website owners can manage their own e-commerce data." on customers
  for all using (exists (select 1 from websites where websites.id = customers.website_id and websites.user_id = auth.uid()));

create policy "Website owners can manage their own e-commerce data." on orders
  for all using (exists (select 1 from websites where websites.id = orders.website_id and websites.user_id = auth.uid()));

create policy "Website owners can manage their own e-commerce data." on order_items
  for all using (exists (select 1 from orders where orders.id = order_items.order_id and exists (select 1 from websites where websites.id = orders.website_id and websites.user_id = auth.uid())));


-- Create tables for analytics
create table internal_analytics (
  id bigint generated by default as identity primary key,
  event_type text,
  template_id bigint references templates,
  user_id uuid references auth.users,
  timestamp timestamptz default now()
);

create table client_analytics (
  id bigint generated by default as identity primary key,
  website_id bigint references websites not null,
  event_type text,
  path text,
  user_agent text,
  location jsonb,
  order_id bigint references orders,
  timestamp timestamptz default now()
);

-- Storage for user-uploaded images
insert into storage.buckets (id, name)
values ('user_images', 'user_images');

create policy "Users can upload images."
  on storage.objects for insert
  with check ( auth.uid() is not null );

create policy "Users can view their own images."
  on storage.objects for select
  using ( auth.uid() = owner );

create policy "Users can delete their own images."
  on storage.objects for delete
  using ( auth.uid() = owner );
